### ISSUE TITLE
这个是你自己整理的读书笔记？

### ISSUE THREAD

**Issue by moooofly** [wuYin/k8s-in-action#1]
RT

**Comment by wuYin** [comment]
是的，原书在 2017.12 出版，中文版由七牛云翻译后在 2019.1 出版。

亮点：
- Pod、Service、Volume、ConfigMap、Deployment 等 k8s 基础概念都解释得很详细，适合新手。
- 文中有大量结构流程图，易于理解。

缺点：
- 有的概念解释篇幅过长，所以自己精简下写了这篇笔记。

k8s 新手值得一读。
